# Generated by Django 6.0 on 2025-12-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_tag_thread_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="thread",
            name="category",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="forum.category",
            ),
            preserve_default=False,
        ),
    ]
