# Generated by Django 6.0 on 2025-12-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "permissions": [
                    ("view_report_page", "Can view a page with all the reports")
                ]
            },
        ),
    ]
